# ~/.zshrc - Ghostty + development shell, tuned for fast startup.

# ----- Paths ---------------------------------------------------------------
# Keep this section pure shell: no `brew shellenv` or other startup subprocesses.
typeset -U path fpath

for dir in \
  "/opt/homebrew/sbin" \
  "/opt/homebrew/bin" \
  "/usr/local/sbin" \
  "/usr/local/bin" \
  "$HOME/.local/share/nvim/mason/bin" \
  "$HOME/.bun/bin" \
  "$HOME/go/bin" \
  "$HOME/.cargo/bin" \
  "$HOME/bin" \
  "$HOME/.local/bin"; do
  [[ -d "$dir" ]] && path=("$dir" "$path[@]")
done
export PATH

for dir in \
  "/opt/homebrew/share/zsh/site-functions" \
  "/opt/homebrew/share/zsh-completions" \
  "/usr/local/share/zsh/site-functions" \
  "/usr/local/share/zsh-completions"; do
  [[ -d "$dir" ]] && fpath=("$dir" "$fpath[@]")
done

# ----- History -------------------------------------------------------------
HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000

setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt HIST_NO_STORE
setopt NO_HIST_BEEP

# ----- Shell Behavior ------------------------------------------------------
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_MINUS
setopt AUTO_NAME_DIRS
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
setopt AUTO_MENU
setopt EXTENDED_GLOB
setopt INTERACTIVE_COMMENTS
setopt LONG_LIST_JOBS
setopt NOTIFY
unsetopt BEEP
unsetopt NOMATCH
unsetopt CORRECT
unsetopt CORRECT_ALL
bindkey -e

# ----- Oh My Zsh -----------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="${ZSH_CUSTOM:-$ZSH/custom}"
ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh"
mkdir -p "$ZSH_CACHE_DIR" 2>/dev/null
ZSH_COMPDUMP="$ZSH_CACHE_DIR/zcompdump-${HOST%%.*}-${ZSH_VERSION}"

zstyle ':omz:update' mode disabled
DISABLE_AUTO_TITLE=true
DISABLE_UNTRACKED_FILES_DIRTY=true
HYPHEN_INSENSITIVE=true

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
ZSH_AUTOSUGGEST_USE_ASYNC=true

if (( $+commands[starship] )); then
  ZSH_THEME=""
else
  ZSH_THEME="robbyrussell"
fi

plugins=(git sudo colored-man-pages)
[[ -d "$ZSH_CUSTOM/plugins/fzf-tab" ]] && plugins+=(fzf-tab)
[[ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]] && plugins+=(zsh-autosuggestions)
if [[ -d "$ZSH_CUSTOM/plugins/fast-syntax-highlighting" ]]; then
  plugins+=(fast-syntax-highlighting)
elif [[ -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]]; then
  plugins+=(zsh-syntax-highlighting)
fi

# Completion behavior. These are read by compinit/OMZ and fzf-tab.
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$ZSH_CACHE_DIR/zcompcache"
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' matcher-list \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*'
zstyle ':fzf-tab:*' fzf-command fzf
zstyle ':fzf-tab:*' switch-group '<' '>'
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always "$realpath" 2>/dev/null || ls -1 "$realpath"'

if [[ -r "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
else
  autoload -Uz compinit
  compinit -d "$ZSH_COMPDUMP"
fi

# ----- Prompt + Tool Hooks -------------------------------------------------
if (( $+commands[starship] )); then
  eval "$(starship init zsh)"
fi

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
fi

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

if (( $+commands[fzf] )); then
  export FZF_DEFAULT_OPTS='--height=40% --layout=reverse --border --inline-info'
  if (( $+commands[fd] )); then
    export FZF_DEFAULT_COMMAND='fd --hidden --strip-cwd-prefix --exclude .git'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d --hidden --strip-cwd-prefix --exclude .git'
  fi
  if (( $+commands[bat] )); then
    export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:200 {} 2>/dev/null'"
  fi
  for fzf_file in \
    "/opt/homebrew/opt/fzf/shell/completion.zsh" \
    "/opt/homebrew/opt/fzf/shell/key-bindings.zsh" \
    "/usr/local/opt/fzf/shell/completion.zsh" \
    "/usr/local/opt/fzf/shell/key-bindings.zsh"; do
    [[ -r "$fzf_file" ]] && source "$fzf_file"
  done
fi

# ----- Editor, Pager, Color ------------------------------------------------
if (( $+commands[nvim] )); then
  export EDITOR="${EDITOR:-nvim}"
else
  export EDITOR="${EDITOR:-vim}"
fi
export VISUAL="${VISUAL:-$EDITOR}"
export PAGER="${PAGER:-less}"
export LESS='-R'
export COLORTERM=truecolor

if (( $+commands[bat] )); then
  export MANPAGER="sh -c 'col -bx | bat --language=man --plain'"
fi

# ----- Aliases -------------------------------------------------------------
alias reload='source ~/.zshrc'
alias path='print -l $path'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias g='git'
alias gs='git status --short --branch'
alias ga='git add'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gp='git push'
alias gl='git pull --ff-only'
alias gd='git diff'
alias gds='git diff --staged'
alias gb='git branch'
alias gco='git checkout'

if (( $+commands[eza] )); then
  alias ls='eza --icons=auto --group-directories-first'
  alias ll='eza -lah --git --icons=auto --group-directories-first'
  alias la='eza -la --icons=auto --group-directories-first'
  alias lt='eza --tree --level=2 --icons=auto --group-directories-first'
else
  alias ll='ls -lah'
  alias la='ls -la'
fi

if (( $+commands[bat] )); then
  alias b='bat'
  alias bp='bat --paging=always'
fi

if (( $+commands[fd] )); then
  alias fd='fd --hidden --exclude .git'
fi

if (( $+commands[rg] )); then
  alias rg='rg --smart-case --hidden --glob "!{.git,node_modules,dist,build,.next,coverage}"'
fi

(( $+commands[lazygit] )) && alias lg='lazygit'
(( $+commands[kubectl] )) && alias k='kubectl'
(( $+commands[docker] )) && alias d='docker'
(( $+commands[docker] )) && alias dc='docker compose'
(( $+commands[python3] )) && alias py='python3'
(( $+commands[python3] )) && alias serve='python3 -m http.server'

# A few deliberate global aliases for pipelines.
alias -g J='| jq'
alias -g C='| pbcopy'
alias -g L='| less -R'
alias -g NUL='>/dev/null 2>&1'

# Named directories: `cd ~work`, `ls ~cfg`, etc.
[[ -d "$HOME/workbench" ]] && hash -d work="$HOME/workbench"
[[ -d "$HOME/Downloads" ]] && hash -d dl="$HOME/Downloads"
[[ -d "$HOME/.config" ]] && hash -d cfg="$HOME/.config"

# ----- Functions + Key Bindings -------------------------------------------
mkcd() {
  mkdir -p "$1" && cd "$1"
}

croot() {
  local root
  root="$(git rev-parse --show-toplevel 2>/dev/null)" || return
  cd "$root"
}

autoload -Uz zmv
alias zcp='noglob zmv -C'
alias zln='noglob zmv -L'

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey ' ' magic-space
bindkey '^[e' edit-command-line
bindkey '^[b' backward-word
bindkey '^[f' forward-word
bindkey '^[[1;3D' backward-word
bindkey '^[[1;3C' forward-word
